spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/ssm
    username: root
mybatis:
  mapper-locations: classpath:/mapper/*.xml

